export const welcomeRoute = '/welcome'
export const loginRoute = '/login'
export const signUpRoute = '/signup'
export const confirmSignupRoute = '/confirm-signup'
export const resetRoute = '/reset'
export const confirmResetRoute = '/confirm-reset'

export const profileRoute = '/profile'
export const profilesRoute = '/profiles'
export const homeRoute = '/home'