name: Build Dev

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Dev Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Webapp - Install dependencies
        run: |
          npm ci

      - name: Webapp - Build
        env:
          NODE_ENV: production
        run: |
          npm run build