name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Prod Job
    runs-on: ubuntu-latest
    env:
      CDK_STACK_NAME: prod-AkuratWebappStack
      CDK_DIFF_OUT_FILE: diff.out
      CDK_OUTPUTS_FILE: outputs.json
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            cdk/package-lock.json

      - name: Webapp - Install dependencies
        run: |
          npm ci

      - name: Webapp - Test
        env:
          CI: true
        run: |
          npm test

      - name: Webapp - Build
        env:
          NODE_ENV: production
        run: |
          npm run build

      - name: CDK - Install dependencies
        working-directory: ./cdk
        run: |
          npm ci

      - name: CDK - Build
        working-directory: ./cdk
        run: |
          npm run build

      - name: CDK - Install dependencies
        working-directory: ./cdk
        run: |
          npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Copy stack cfn parameters from S3 bucket and set as cdk context
        working-directory: ./cdk
        run: |
          aws s3 cp s3://akurat-artifacts/distribution/prod/config.json cdk.context.json

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: AWS CDK synth
        working-directory: ./cdk
        run: |
          cdk synth ${{ env.CDK_STACK_NAME }}

      - name: AWS CDK diff
        working-directory: ./cdk
        run: |
          cdk diff ${{ env.CDK_STACK_NAME }} --ci >> ${{ env.CDK_DIFF_OUT_FILE }}

      - name: Archive AWS CDK diff outputs
        uses: actions/upload-artifact@v3
        with:
          name: cdk-diff-outputs
          path: cdk/${{ env.CDK_DIFF_OUT_FILE }}

      - name: AWS CDK deploy
        working-directory: ./cdk
        run: |
          cdk deploy ${{ env.CDK_STACK_NAME }} --require-approval never --ci --outputs-file ${{ env.CDK_OUTPUTS_FILE }}

      - name: Archive AWS CDK deployment outputs
        uses: actions/upload-artifact@v3
        with:
          name: cdk-deploy-outputs
          path: cdk/${{ env.CDK_OUTPUTS_FILE }}